Fast:
	g++ -std=c++11 -pipe -O2 -lm -s -fomit-frame-pointer -o Wrong.out Wrong.cpp
	./Wrong.out

Slow:
	g++ -std=c++11 -o Wrong.out Wrong.cpp
	./Wrong.out

Debug:
	g++ -std=c++11 -g -o Wrong.out Wrong.cpp
	gdb -tui Wrong.out

